# Домашнее задание «Библиотека numpy. Вычислительные задачи»

## Задание 1

In [2]:
import numpy as np

In [4]:
N = 10

np.arange(0, N)[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## Задание 2

In [5]:
N = 5

a = np.zeros((N, N), int)

np.fill_diagonal(a, np.arange(0, N)[::-1])

a

array([[4, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0]])

## Задание 3

In [6]:
# 4x + 2y + z = 4
# x + 3y = 12
# 5y + 4z = -3

In [8]:
A = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
B = np.array([4, 12, -3])
X = np.linalg.solve(A,B)
X_r = np.around(X, decimals = 2)

print(X_r)

[ 0.47  3.84 -5.56]


In [9]:
# check

np.allclose(np.dot(A, X), B)

True